steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/discord-node-app/discord-node-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/discord-node-app/discord-node-app"]
