steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/discord-node-app/discord-node-app:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/discord-node-app/discord-node-app:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "INSTANCE_NAME"
      - "--container-image=gcr.io/discord-node-app/discord-node-app:latest"
      - "--zone=northamerica-northeast1-a"
      - "--metadata=_INSTANCE_TEMPLATE=instance-template-1"

substitutions:
  _INSTANCE_NAME: instance-2
